server:
  port: 9301
  address: 0.0.0.0

spring:



  application:
    name: dding-user-review-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/reservation
    username: root
    password: 1001
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
