server:
  port: 9601
spring:
  application:
    name: dding-BandRoom-HRoomStudio-servicev2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/studio
    username: root
    password: 1001
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
