server:
  port: 9020
spring:
  application:
    name: dding-bandroom-room-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bandroom
    username: root
    password: 1001
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none


address-service:
  url: http://localhost:9022